# Generated by Django 3.2.5 on 2022-05-01 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_order_orderinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='fooditem',
            new_name='foodItem',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_infos', to='coreapp.order'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='subtotal',
            field=models.FloatField(),
        ),
    ]
